name: ASCII Workflow
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Execute shell script
              run: ./ascii-script.sh
